language: go

sudo: false

matrix:
  include:
    - go: 1.x
      env: RELEASE=true
    - go: master
  allow_failures:
    - go: master

after_success:
  - go build -ldflags="-s -w"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: HJlWBwOtN025nqtvR8OnS4z9aVYVxgUCkLEni8tyVAicvGBkmYvIQf8ZDaLXLjvvUyk/SOiLEQZSMNYAb92jxF+xNspPmTylAenxQfFvXFMzFwGgOJpL0O0PhDjCIZXW62ROHEdsMwPEHh6wCaxxSPilSnso0mjcgdv2JeGvHTFe1/tzPOtQUqdaHqqJsJW3ZefWnyvurtycrAEcCELI5o1Ud9ulpI1jURJ2rd2l/IR9ivTiYkEak9+xoXlSnGpW7LwM4weUuFrQx51HD9tiD/2k+wmEkbwe0i/4jJj9jsChv8K4ebNVMv591sb64DdtMRbfRDb3xo+cDqMSk/y2N0E5Hp+CftqPne37EzMRUFSYjx2BkayeuDUAwJxsPs3eO7UnkO4FL1cjiDLYV7dT5wr9r+WQHsZD1JkUfIVET8X1/CuzXTGLzRm8mtkzEI+9amhtPC51hLjuLV4QXfjKcY23pVTb223+gmE4i4si3O6nQkwlTqbjZgFN7H4i9AGZClOZN7+WZM7adG2iNxjFSRo71HV/mtmO/bbCefGKXtzTgQoxdXJYCvNFVDQVRJFk0WwesEquzo2VnjNCfbVpeuLvo8U5EaMw/o8Y8KaqQghVEnGJE1vMhb0t64+ZB8GMne+kwZRmDiOYhYQmRUot8NS3W8V7EWOd0B4BMPmTpmQ=
  file: smtp-dkim-signer
  on:
    tags: true
    repo: mback2k/smtp-dkim-signer
    condition: $RELEASE = true
