name: Build & Release

on:
  push:
    branches: [ master ]
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Vet
        run: go vet -v ./...
        env:
          GO111MODULE: on

      - name: Build
        run: go build -v ./...
        env:
          GO111MODULE: on

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: smtp-dkim-signer
          path: ./smtp-dkim-signer
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: smtp-dkim-signer

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifact: "smtp-dkim-signer"
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
